---
- name: Creazione Registry e Container
  hosts: rocky
  become: yes

  vars:
    container_runtime: "docker"  # o "podman"
    first_container_image: "alessandrotofani/track3_step2:2.1"
    first_container_name: "ubuntu"
    first_container_port: 4797
    second_container_image: "alessandrotofani/track3_step2:1.1"
    second_container_name: "rocky"
    second_container_port: 4536
    image_name: "image_test"
    image_tag: "1.2.2"
    Dockerfile_PATH: "/Users/alessandro.tofani/Desktop/formazione_cm/Step3/roles/"
    registry_host: "registry"
    registry_port: "5000"
  
  roles:
    - prerequisiti
    - Containers
    - Build_push


  

      

   

      
