pipeline {
    agent any

    environment {
        REPO_DIR = 'formazionesou_cm'
        REPO_URL = 'https://github.com/Alessandro-Tofani-GIT/formazione_cm'
        TAG_registry = "${BUILD_NUMBER}"
        Container_Name= 'test_docker_in_docker'
    }

    stages {
        stage('clone or pull') {
            steps {
                script {
                    if (!fileExists(REPO_DIR)) {
                        echo "Clonando il repo ${REPO_URL}"
                        sh """
                            git clone ${REPO_URL} ${REPO_DIR}
                            cd ${REPO_DIR}
                            ls -la && pwd
                        """
                    } else {
                        echo "${TAG_registry}"
                        echo "Pull Repository"
                        sh """
                            cd ${REPO_DIR}
                            git pull origin main
                            ls -la

                            # Directory dove si trova il Dockerfile
                            cd Step5/Docker_Image

                            # Controllo e generazione chiavi SSH solo se non esistono
                            KEY_PATH="ssh_keys/id_rsa"
                            mkdir -p ssh_keys

                            if [ ! -f "\$KEY_PATH" ] || [ ! -f "\${KEY_PATH}.pub" ]; then
                                echo "Chiavi SSH non trovate, le genero..."
                                ssh-keygen -t rsa -b 4096 -f "\$KEY_PATH" -N ""
                            else
                                echo "Chiavi SSH già presenti, salto la generazione."
                            fi

                            # Costruisco, pusho e avvio il container
                            sudo docker build -f Dockerfile -t 172.17.0.1:5000/docker-in-docker:${TAG_registry} .
                            sudo docker images
                            sudo docker push 172.17.0.1:5000/docker-in-docker:${TAG_registry}

                            sudo docker run -d --name ${Container_Name} -p 2222:2222 172.17.0.1:5000/docker-in-docker:${TAG_registry}
                            sudo docker ps -a
                        """
                    }
                }
            }
        }
    }
}