---
- name: Installa Docker e configura il registry
  hosts: localhost

  vars:
    container_image: alessandrotofani/track3_step2:2.1 
    container_name: Ubuntu
    container1_image: alessandrotofani/track3_step2:1.1
    container1_name: ROCKY
      
  

  tasks:

    - name: Avvia un container test
      community.docker.docker_container:
        name: "{{container1_name}}"
        image: "{{container1_image}}"
        state: started
        published_ports:
          - "5019:22"

    - name: Avvia Registry Docker
      community.docker.docker_container:
        name: "{{container_name}}"
        image: "{{container_image}}"
        state: started
        restart_policy: always
        published_ports:
          - "5632:22"
        
      